export enum DepartmentsActionTypes {
  DEPARTMENTS_LIST_REQUEST = 'DEPARTMENTS_LIST_REQUEST',
  DEPARTMENTS_LIST_RESPONSE = 'DEPARTMENTS_LIST_RESPONSE',
  DEPARTMENTS_LIST_FAIL = 'DEPARTMENTS_LIST_FAIL',
}